name: verify-ci-status
description: Verifies that a CI status is passing before proceeding.
inputs:
  GITHUB_TOKEN:
    required: true
  name:
    required: false
    default: Jenkins
runs:
  using: composite
  steps: 
    - run: GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }} NAME=${{ inputs.name }} $GITHUB_ACTION_PATH/run.sh
      shell: bash
